# In netlify.toml
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"